### ISSUE TITLE
FE: Implement Copy Functionality of Shortened Link (Create a Link)

### ISSUE THREAD

**Issue by reesegreen2014** [turingschool/turlink-fe#25]
- [x] Create Copy component that has input field, copy button, and displays original URL enter by the user
- [x] Use navigator.clipboard.writeText(input.value) to copy value entered into 
- [x] Provide user feedback, such as "copied to clipboard"
- [ ] Confirm the functionality works for different browsers and devices (i.e., mobile phone)

**Comment by zachwolek** [comment]
Create Copy component was integrated into <ShortenedLinkPage/>
